name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Jekyll Builder for GitHub Pages
      uses: fabacab/jekyll-builder-for-github-pages-action@v1
      with:
        gh_pages_publishing_source: gh-pages
        git_commit_message: Update Sites from run ${{github.run_id}}
        git_committer_email: 'contact@usegalaxy.eu'
        git_commiter_name: 'GH Actions Bot'
